proxy:
  image: nginx:stable
  links:
    - app
  ports:
    - "8080:8080"
  volumes:
    - ./build/docker/proxy/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template:ro
    - ./build/docker/proxy/includes:/etc/nginx/conf.d/includes:ro
    - ./web:/usr/share/nginx/www/spenden.wikimedia.de/current/web:ro
    - ./vendor/wmde/fundraising-frontend-content/resources:/usr/share/nginx/www/spenden.wikimedia.de/current/web/resources:ro
  environment:
    - NGINX_HOST=spenden.wikimedia.de
    - NGINX_PORT=8080
  command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

app:
  build: ./build/docker/app
  expose:
    - "9000"
  volumes:
    - .:/usr/share/nginx/www/spenden.wikimedia.de/current

# This is a PoC
# Many files are shameless copies of other files from this repo / infrastructure
# Has to be consolidated before actual use to mitigate unmaintainable duplication

# view in browser via
# http://localhost:8080/

# run tests via
# $ docker-compose run -w /usr/share/nginx/www/spenden.wikimedia.de app vendor/bin/phpunit
